[package]
name = "IOT_B3"
version = "0.1.0"
authors = ["Muhammad Salee <msaleembhatti@hotmail.com>"]
edition = "2018"
description="a simple function"
license = "MIT/Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
